---
title: "**06wk-1**: 확률을 잘 정의할 수 있을까?"
author: 최규빈
date: "10/07/2026 09:00"
draft: false
format:
  html:
    header-includes: |
      <style>
      table { width: auto !important; margin-left: auto !important; margin-right: auto !important; }
      </style>
---

# 1. 강의영상

{{<video https://youtu.be/playlist?list=PLU2mHqL7__cA&si=bqjJTsTJcY68zjdd>}}

# 2. 동전던지기 예제

`-` 예제상황

- $\Omega =\{H,T\}$: sample space 
- $P(\{H\})=P(\{T\})=\frac{1}{2}$: prob

`-` 질문: $\Omega$의 임의의(=모든) 부분 집합 $\Omega^*$에 대하여 $P(\Omega^*)$를 **모순없이** 정의할 수 있을까? 

- 당연한거 아냐?
- 이게 왜 안돼?

`-` 질문에 대한 대답

| $\Omega^\ast$의 후보 | 확률                                    |
| ----------------- | ------------------------------------- |
| $\{H\}$           | $P(\Omega^\ast)=P(\{H\})=\frac{1}{2}$ |
| $\{T\}$           | $P(\Omega^\ast)=P(\{T\})=\frac{1}{2}$ |
| $\Omega$          | $P(\Omega^\ast)=P(\Omega)=1$          |
| $\emptyset$       | $P(\Omega^\ast)=P(\emptyset)=0$       |

<!-- colwidths: 9.4 9.4 -->


`-` **모순없이**의 의미? (조금 informal한 설명) 

- 우리가 상식적으로 확률에 적용가능한 어떠한 연산들이 있음. (확률의 공리 + 기본성질) // [네이버검색](https://deep-learning-study.tistory.com/40#:~:text=%EA%B3%B5%EB%A6%AC%201%EC%9D%80%20%EC%96%B4%EB%96%A4%20%EC%8B%A4%ED%97%98,%EA%B3%BC%20%EA%B0%99%EC%9D%8C%EC%9D%84%20%EC%9D%98%EB%AF%B8%ED%95%A9%EB%8B%88%EB%8B%A4.)
- 이러한 연산을 적용해도 상식적인 수준에서 납득이 가야함. 

`-` **상식적인 연산 적용 예시1**

$$\{H\} \subset \Omega \Rightarrow P(\{H\})<P(\Omega)$$

- 집합 $\{H\}$은 집합 $\Omega$보다 작은 집합임 
- 상식적으로 작은집합이 일어날 확률이 큰 집합이 일어날 확률보다 클 수 없음
- 동전 예제의 경우 모든 $A,B \subset \Omega$ 에 대하여, $A\subset B$ 이라면 $P(A) < P(B)$ 가 성립함 

`-` **상식적인 연산 적용 예시2**

$$\{H\} \cap \{T\} = \emptyset \Rightarrow P(\{H\} \cup \{T\})=P(\{H\}) + P(\{T\}) =1$$ 

- 우리의 상식에 따르면 $A,B$가 서로소인 사건이라면 $P(A)+P(B)$이어야 함.^[확률의 공리]
- 이 예제는 실제로 그러함. 
- 사실 이 예제의 경우 $P(\{H\} \cup \{T\})=P(\Omega)=1$ 와 같이 계산할 수도 있음. 
- 하지만 어떠한 방식으로 계산해도 **모순이 없음**. 

`-` 그 외의 상싱적인 연산도 모두 잘 성립한다. (여집합 같은거) 

# 3. 예제2: 바늘이 하나만 있는 시계

`-` 예제상황:

- 시계바늘을 돌려서 나오는 각도를 재는일 $\Leftrightarrow$ $[0,2\pi)$사이의 숫자중에 하나를 뽑는 일 
- $\Omega  = [0,2\pi)$

`# 쉬운질문` -- 바늘을 랜덤으로 돌렸을때 12시-6시 사이에 바늘이 있을 확률? $\frac{1}{2}$

어떻게 푸셨나요? (길이의 비를 썼죠?)

`-` 사실 벌써 살짝 거슬리는 부분이 있습니다. 12시-6시 사이가 의미하는게 $[0,\pi]$ 인지 $(0,\pi)$ 인지 $[0,\pi)$ 인지 $(0,\pi]$ 인지 애매하지 않나요? 아무렇게나 해도 상관없지만 (이따가 이유설명) 우선은 $\Omega=[0,2\pi)$ 라고 두었고 전체구간의 길이를 $2\pi$라고 생각하면 편리하니까 12시-6시도 $[0,\pi)$라고 두고 아래와 같이 정리하면 좋겠습니다. 

- $\Omega=[0,2\pi)$ , $\Omega$의 길이는 $2\pi$
- $\Omega^* = [0,\pi)$, $\Omega^\ast$의 길이는 $\pi$
`#`

`-` 이 예제에서 $P(\Omega^\ast)$를 계산하는 방법? 아래와 같이 계산하면 가능!!



$$\forall \Omega^* \subset \Omega, \quad P(\Omega^*)=\frac{m(\Omega^*)}{m(\Omega)}$$

단 여기에서 $m$은 구간의 길이를 재는 함수라고 하고, 구간 $[a,b)$꼴의 길이는 $b-a$라고 하자. 

`-` **연습:** $m$의 사용 

- $m(\Omega)=m\big([0,2\pi)\big)=2\pi$
- $m(\Omega^*) = m\big([0,\pi)\big)= \pi$

`-` 그렇다면 아래와 같은 방식으로 확률을 정의하면 잘 정의될까? 

$$\forall \Omega^* \subset \Omega, \quad P(\Omega^*)=\frac{m(\Omega^*)}{m(\Omega)}$$

이게 쉽지 않음. 왜냐하면 확률을 잘 정의하기 위해서는 

> $\Omega$의 모든 부분집합 $\Omega^*$에 대하여 $P(\Omega^*)$를 모순없이

정의할 수 있어야 하는데, 이게 쉬운일이 아님. 

---

`# 질문1` -- $\Omega^*=\emptyset$ 일 확률이 얼마인가? 
 
(답변)

0 이에요 (이걸 좀 더 엄밀하게 따질수도 있는데 일단 직관적으로 0이라 생각하고 넘어가자)

`#`

---

`# 질문2` -- $\Omega^* =\{0\}$일 확률이 얼마인가?
 
(답변)

`-` 질문을 정리하면 바늘침이 정확하게 12시를 가르킬 확률이 얼마냐고 묻는 것이다. 

`-` 짜증나지만 답변을 안 할 수는 없다. 

- 우리는 $\Omega$의 부분집합중 어떠한 $\Omega^\ast$를 가져와도 확률을 정의할 수 있다고 주장하고 있음.
- 질문에서 가지고 온 집합 $\{0\}$은 분명히 구간 $[0,2\pi)$의 부분집합임. 
- 따라서 우리는 이러한 집합 "$\Omega=\{0\}$"에 대해서도 답변할 "의무"가 있음. (그걸 못하겠다면 "$\Omega$의 모든 부분집합 $\Omega^*$에 대하여 (당연히) $P(\Omega^*)$를 모순없이 정의 할 수 있다" 라는 우리의 주장을 철회해야함. 

`-` 답변?

- 많은 사람들이 이 질문에 대한 답은 $0$ 이라고 알고 있음.
- 그 이유를 "점의 길이는 0 이니까" 라고 이해하고 있음.
- 이해 안되면 약속이라고 생각하자.

`-` 답변이 사실 좀 찝찝하다.

-  바늘침이 정확하게 12시를 가르키는 것은 우리가 분명 하루에 한번씩은 경험하는 사건임. 
- 그런데 그 사건이 일어날 확률은 0이다? (자연어에서는 "확률=0" 와 "불가능" 은 동일하지만 여기서는 아니다.)

`#`

---

`# 질문3?` -- 생각해보니까 이런게 있었잖아요?

$$A \subset B \Rightarrow P(A)<P(B)$$
그런데 $\emptyset \subset \{0\}$ 인데, 우리의 예제에서는 $P(\emptyset)=P(\{0\})=0$ 이네요? 이건 모순 아닌가요? 

(답변)

`-` 모순이 아님. 사실 질문이 잘못되었음. 질문자가 주장하는 성질 "$A \subset B \Rightarrow P(A) < P(B)$" 애초에 존재하지 않음. 

`-` 정확한 버전은 "$A \subset B \Rightarrow P(A)\leq P(B)$ " 임. 

- 여기에서 $A \subset B$는 $A =B$인 상황과 $A \subsetneq B$인 상황으로 모두 포함함. 
- 즉 $A$가 $B$의 진 부분집합이더라도 ($A \subsetneq B$ 이더라도) $P(A)=P(B)$인 경우가 존재함. 

`#`

---

`# 질문4` -- 그렇다면 사건 $\{0,\pi\}$가 일어날 확률은 얼마인가?

(답변)

`-` 질문을 다시 풀어쓰면 바늘침이 정확하게 12시를 가르키거나 혹은 정확하게 6시를 가르킬 확률이 얼마냐는 것. 

`-` 따라서 이 질문에 대한 대답은 $0+0=0$ 이므로 $0$이라고 주장할 수 있음.

---

`# 질문5` -- 구간 $[0,2\pi)$는 무수히 많은 점들이 모여서 만들어지는 집합이다. 그런데 점 하나의 길이는 0이다. 0을 무수히 더해도 0이다. 그러므로 구간 $[0,2\pi)$의 길이도 0이 되어야 한다. 이것은 모순아닌가?

(답변)

`-` 까다롭다. 

`-` $m([0,2\pi))=0$ 임을 인정하면 전체확률은 1이어야 한다는 기본상식^[심지어 이건 확률의 공리]에 어긋나 모순이 생김.

`-` 질문의 논리는 타당해보임. 이 논리의 약점은 딱히 없어보임. 굳이 약점이 있다면 "무한"이라는 개념?

`-` 어쩔수없이 직관에 근거한 약간의 약속을 또 다시 해야할 것 같음. 예를들면 "점들을 유한번 합치면 그냥 많은 점들이지만 무한히 합치면 이것은 선분이 된다. 따라서 길이가 생긴다." 와 같이.

`-` 우리는 이 약속을 "무한번의 기적"이라고 칭하자.

`#`

---

`# 질문6` -- $[0,\pi)$ 에서 유리수만 뽑아낸 집합이 있다고 생각하자. 편의상 이 집합을 $\mathbb{Q}$ 라고 하자. 이 집합은 분명히 무한개의 점을 포함하고 있다. 그렇다면 이 집합도 길이가 있는가? 있다면 얼마인가?

(답변)

`-` 짜증난다. 

`-` 이미 점들의 길이를 무한번 더하면 길이가 생긴다고 주장한 상태이므로 (무한번의 기적) 길이가 0이라고 주장할 수 없다. 따라서 길이가 있다고 주장해야 한다. 
	
- 거의 질문5 때문에 목덜미 물린 상황임. 

`-` 길이를 뭐라고 말해야 할까? 

- $\pi$말고 딱히 떠오르는 수가 없는데 단순히 길이가 $\pi$라고 주장한다면 바로 모순에 빠짐을 알 수 있다. (왜?)
- 길이는 일단 0보다 커야하고 $\pi$보다 작아야함은 자명하므로 그 사이에 있는 어떤 값이 길이라고 주장하자. 구체적으로 어떤값인지는 모른다고 하자. (왜 그 값이냐고 물으면 근거가 없으니까) 
- 따라서 이 질문에 대한 답은 ''구체적으로 얼마인지는 모르겠지만 길이가 분명 존재하고 그 길이는 0 보다 크고 $\pi$ 보다는 작은 어떠한 값 $a$이다.'' 정도로 정리할 수 있다. 

`-` 결론: $m(\mathbb{Q})=a$, 단 $0<a <\pi$. 

`#`

---

`# 질문7` -- 질문6로부터 만들어지는 논리는 빌드업1-3으로 이어지는 콤보질문을 적절하게 대답하지 못한다. (질문이 좀 길어서 나누어서 설명합니다)

`■□□ 빌드업1` -- 평행이동은 길이를 변화시키지 않아, 그렇지?

- $\mathbb{Q}$의 모든점에 $\sqrt{2}$를 더한다. 이 점들로 집합을 만들어 $\mathbb{Q}_{\sqrt{2}}$를 만든다. 
- 여기에서 $\mathbb{Q}_{\sqrt{2}}$는 $\Omega$의 부분집합 $\Rightarrow$ $\mathbb{Q}_{\sqrt{2}}$는 길이를 **명확하고 모순없이** 정의할 수 있어야 함
- $\mathbb{Q}_{\sqrt{2}}$의 길이는 사실 쉽게 $a$라고 정의할 수 있음^[평행이동은 길이를 변화시킬 수 없으니까]. 즉, $m(\mathbb{Q}_{\sqrt{2}})=a$.

`■■□ 빌드업2` -- 겹치지 않게 평행이동 시킨다음에 길이를 더한다면?

이제 $\mathbb{Q}_{\sqrt{2}},\mathbb{Q}_{\sqrt{2}/2},\mathbb{Q}_{\sqrt{2}/3}$를 생각하자. 아래의 성질을 관찰할 수 있다. 

1. $\mathbb{Q}_{\sqrt{2}},\mathbb{Q}_{\sqrt{2}/2},\mathbb{Q}_{\sqrt{2}/3}$는 모두 $\Omega$의 부분집합 $\Rightarrow$ 따라서 길이를 **명확하고 모순없이** 정의할 수 있어야 함
2. $\mathbb{Q}_{\sqrt{2}},\mathbb{Q}_{\sqrt{2}/2},\mathbb{Q}_{\sqrt{2}/3}$의 길이는 각각 $a$로 정의할 수 있다.^[평행이동은 길이를 변화시키지 않으니까]
3. $P(\mathbb{Q}_{\sqrt{2}} \cup \mathbb{Q}_{\sqrt{2}/2} \cup \mathbb{Q}_{\sqrt{2}/3})=P(\mathbb{Q}_{\sqrt{2}}) + P(\mathbb{Q}_{\sqrt{2}/2})+ P(\mathbb{Q}_{\sqrt{2}/3})$^[$\mathbb{Q}_{\sqrt{2}},\mathbb{Q}_{\sqrt{2}/2},\mathbb{Q}_{\sqrt{2}/3}$는 모두 서로소 임을 이용]
굳이 $P(\mathbb{Q}_{\sqrt{2}}) + P(\mathbb{Q}_{\sqrt{2}/2})+ P(\mathbb{Q}_{\sqrt{2}/3})$를 계산하면 아래와 같이 계산할 수 있겠다. 

$$P(\mathbb{Q}_{\sqrt{2}}) + P(\mathbb{Q}_{\sqrt{2}/2})+ P(\mathbb{Q}_{\sqrt{2}/3})=\frac{a}{2\pi}+\frac{a}{2\pi}+\frac{a}{2\pi}=3 \times \frac{a}{2\pi}$$

`■■■ 빌드업3` -- 그런데 난 겹치지않게 평행이동시킬 방법을 무한대로 알고 있는데?

눈 여겨볼 점은 아래 식이 성립해야 한다는 것이다. ($\because$ 확률의 공리)^[첫 등호는 서로소인 사건에 대한 공리, 그다음 부등호는 확률의 총합은 1보다 같거나 작다라는 공리]

$$P\big(\mathbb{Q}_{\sqrt{2}} \cup \mathbb{Q}_{\sqrt{2}/2} \cup \mathbb{Q}_{\sqrt{2}/3}\big) = 3 \times \frac{a}{2\pi} \leq 1 \quad \cdots (\star)$$
- 그런데 $(\star)$에서 좌변의 값은 편의에 따라서 값을 임의로 키울 수 있다. 
- 이렇게 임의로 키워진 좌변의 값이라도 항상 그 값은 1보다 작아야 하는데 (확률의 공리), 이게 가능하려면 $a=0$인 경우 말고 없다. 
- 그런데 $a=0$ 이 된다면 "무한번 더해서 일어나는 기적"은 허구가 되므로 `질문6` 의 대답에 모순이 된다. 

그런데 임의로 좌변의 값을 키워도 항상 그 값은 1보다 작아야 하는데 이러한 $a$는 0이외에 불가능하다. 그런데 $a=0$ 이 된다면 "무한번 더해서 일어나는 기적"은 허구가 되므로 `질문5` 의 대답에 모순이 된다. 

`#`

---

# 4. 르벡메져

`-` 바늘이 하나뿐인 시계에서의 마지막 질문은 지금까지 제시한 논리로 방어가 불가능. 이처럼 논리적인 모순없는 체계를 만드는 것은 매우 어려운 일임. 

`-` 결론적으로 말하면 길이를 재는 함수 $m$을 아래와 가정하면 위의 모든 질문에 대한 대답을 논리적 모순없이 설계할 수 있다. 

1. 한 점에 대한 길이는 $0$ 이다. 
2. $[0,2\pi)$ 사이의 모든 유리수로 이루어진 집합은 그 길이가 $0$이다. 
3. $[0,2\pi)$ 사이의 모든 무리수로 이루어진 집합은 그 길이가 $2\pi$이다. 

참고로 르벡측도(Lebesgue measure)를 사용하면 위의 성질을 만족한다. (물론 르벡측도의 정의가 위와 같지는 않다) 따라서 르벡측도를 활용하여 확률을 정의하는 것이 모순을 최대한 피할 수 있다. 

`-` 우리는 $[0,2\pi)$사이의 모든 유리수로 이루어진 집합은 그 길이가 0이지만 모든 무리수로 이루어진 집합은 그 길이가 0이 아니라는걸 어떻게 받아들여야 할까?
